# Generated by Django 5.2.6 on 2025-11-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('edition', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
